spring:
  application:
    name: Car-service-agency
  datasource:
    url: jdbc:mysql://localhost:3306/carservicedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update